#!/bin/bash

# This piece of code adds all of the public keys in keys folder to the 
# specifc remote server given as the first arg
# example: add-em-to 192.168.1.100

REMOTE=$1
FILES='keys/*'
TMP='keys/tmp'
HOME='/root'

touch $TMP
for item in $FILES
do
	cat $item >> $TMP
	sleep 1
	#ssh-copy-id -i $item $REMOTE
done

scp $TMP $REMOTE:$HOME/.ssh/
ssh $REMOTE cat $HOME/.ssh/tmp >> $HOME/.ssh/authorized_keys && rm $HOME/.ssh/tmp
rm $TMP

cat $HOME/.ssh/authorized_keys
