#!/bin/bash

COUNT=$1
DB_NAME='dbname'
DB_HOST='127.0.0.1'
DB_USER='root'
DB_PASS='root'

for i in $(seq $COUNT); do
	UUID=`uuidgen`
        echo $UUID >> ./tmp
	UUID="'`uuidgen`'"
	SQL='INSERT INTO project_coupon (uuid) VALUES ('$UUID');'
	echo $SQL
	#mysql -u $DB_USER -p$DB_PASS -h $DB_HOST --database=$DB_NAME --execute=$SQL
done
cat ./tmp
rm ./tmp
