#!/bin/bash
# This script is the simplest way to add a OSD (Object Storage Daemon)
# to an specifed ceph cluster
# Ceph is a Distirbuted File System cluster solution http://ceph.com/

# TODO: check the Block device validity
# TODO: Before running this script you have to check if at least one Monitor be 
# added to chech cluster
# TODO: check the validity of first argument if the specified cluster exist or note

progress(){
	# color code constants
	red=`tput setaf 1`
	green=`tput setaf 2`
	reset=`tput sgr0`
	# variables
	progress=10
	is_ok=$1
	msg=$2

	for i in `seq 1 $progress`
	do
		echo -n "."
		sleep 0.2s
	done
	if [ "$is_ok" -eq "1" ];then
		echo -ne " [ ${green}${msg}${reset} ]\n"
	else
		echo -ne " [ ${red}${msg}${reset} ]\n"
	fi
}


if [ "$1" == "-h" ]; then
	echo "usage: ./ceph-add-osd cluster_name disk_block_device"
	echo "example: ./ceph-add-osd ceph /dev/sdb1"
	exit 0
fi

CLUSTER=$1
DISK_DEV=$2
HOST=`cat /etc/hostname`
OSD_NUM=`ceph osd create`


if ! [ -f /etc/initd/ceph ];then
	progress 0 "ceph is not installed"
	read -p "Do you want to install ceph package: (Y/n) " prompt
	if [ \( "$prompt" = "Y" \) -o \( "$prompt" = "y" \) ];then
		sudo apt-get update
		sudo apt-get install ceph
		echo "ceph installed successfully :)"
	else
		if [ "$prompt" = "n" ];then
			echo -ne "\nScript will now terminate "
			progress 1 "Good luck!"
			exit 0
		fi
		exit 0
	fi
else
	progress 1 "ceph is already installed"
fi


mkdir /var/lib/ceph/osd/ceph-$OSD_NUM

mkfs -t xfs -f $DISK_DEV

mount $DISK_DEV /var/lib/ceph/osd/ceph-$OSD_NUM
mount -o remount,user_xattr $DISK_DEV /var/lib/ceph/osd/ceph-$OSD_NUM
ceph-osd -i $OSD_NUM --mkfs --mkkey
ceph auth add osd.$OSD_NUM osd 'allow *' mon 'allow profile osd' -i /var/lib/ceph/osd/ceph-$OSD_NUM/keyring
ceph --cluster $CLUSTER osd crush add-bucket $HOST host
ceph osd crush move $HOST root=default
ceph osd crush add osd.$OSD_NUM 1.0 host=$HOST
ceph osd in $OSD_NUM
/etc/init.d/ceph -a -v restart
/etc/init.d/ceph start osd.$OSD_NUM
/etc/init.d/ceph -v start osd.$OSD_NUM
touch /var/lib/ceph/osd/ceph-$OSD_NUM/sysvinit
echo "$DISK_DEV	/var/lib/ceph/osd/ceph-$OSD_NUM	xfs	defaults	0	0" >> /etc/fstab
ceph -s
ceph osd tree
