#!/bin/bash

if [ "$1" == "-h" ]; then
        echo "usage: ./ceph-rm-osd OSD_FULL_NAME OSD_NUMBER"
        echo "example: ./ceph-rm-osd osd.1 1"
        exit 0
fi

OSD_NAME=$1
OSD_NUM=$2
CLUSTER="ceph"

ceph osd out $OSD_NUM
/etc/init.d/ceph -v stop $OSD_NAME
umount /var/lib/ceph/osd/ceph-$OSD_NUM
ceph osd crush remove $OSD_NAME
ceph auth del $OSD_NAME
ceph osd rm $OSD_NUM
rm -R /var/lib/ceph/osd/$CLUSTER-$OSD_NUM
ceph -s
ceph osd tree

