#!/bin/bash
clear;

ACTION=$1

if [ "$ACTION" == "-h" ]; then
	echo "usage: ./check_services restart"
	exit 0;
fi
if [ "$ACTION" == "stop" -o "$ACTION" == "start" -o "$ACTION" == "restart" ]; then

	echo -e "\n-------------- $ACTIONing Identity services nova services ----------------\n"
	service keystone $ACTION

	echo -e "\n-------------- $ACTIONing Compute services nova services ----------------\n"
	service nova-api $ACTION
	service nova-cert $ACTION
	service nova-consoleauth $ACTION
	service nova-scheduler $ACTION
	service nova-conductor $ACTION
	service nova-novncproxy $ACTION

	echo -e "\n-------------- $ACTIONing Image services ----------------\n"
	service glance-registry $ACTION
	service glance-api $ACTION

	echo -e "\n-------------- $ACTIONing Networking services ----------------\n"
	service neutron-server $ACTION


	#network node
	service  neutron-dhcp-agent $ACTION
	service  neutron-l3-agent $ACTION
	service  neutron-plugin-openvswitch-agent $ACTION
else
	echo "$ACTION is not a proper parameter pleas retry using {start,stop,restart} parameters."
fi


