#!/bin/sh

export OS_AUTH_URL=http://controller:35357/v2.0
export OS_USERNAME=admin
export OS_PASSWORD=admin
export OS_TENANT_NAME=admin

neutron net-create demo-net
neutron subnet-create demo-net --name demo-subnet --gateway 192.168.1.1 192.168.1.0/24

neutron net-create ext-net --shared --router:external True --provider:physical_network external --provider:network_type flat 
neutron subnet-create ext-net --name ext-subnet --allocation-pool start=172.20.90.111,end=172.20.90.254 --disable-dhcp --gateway 172.20.90.1 172.20.90.0/24
neutron router-create xaas-router
neutron router-interface-add xaas-router demo-subnet
neutron router-gateway-set xaas-router ext-net
